apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: blog-api
  - path: ingress-traefik-patch.yaml # 测试环境 Ingress 路由补丁
    target:
      kind: Ingress
      name: blog-api-ingress
images:
  - name: inkspace-blog-api-image
    newName: https://hub.docker.com/r/iceymoss/blog-api
    newTag: v20251209174000 # CI 脚本将更新此 Tag
