apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-web-ingress
  labels:
    app.kubernetes.io/name: blog-web
    project: inskspace
  annotations:
    # 确保 Traefik 识别
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: placeholder.local # 占位符
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-web
                port:
                  number: 80