apiVersion: v1
kind: Service
metadata:
  name: scheduler-task
  labels:
    app.kubernetes.io/name: scheduler-task
    project: inkspace
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: scheduler-task