apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: admin-web
  - path: ingress-traefik-patch.yaml
    target:
      kind: Ingress
      name: admin-web-ingress

# ！！！ 镜像替换：使用 nginx:alpine
images:
  - name: inkspace-admin-web-image
    newName: nginx
    newTag: alpine