apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# 自动为所有资源加上 inkspace-backend 命名空间
namespace: inkspace-backend

resources:
  - deployment.yaml # 包含 Deployment
  - service.yaml # 包含 Service
  - blog-api-ingress.yaml # 对外暴露服务