apiVersion: v1
kind: Service
metadata:
  name: blog-api # Service 名称
  labels:
    app.kubernetes.io/name: blog-api
    project: inkspace
spec:
  type: ClusterIP # 使用 ClusterIP，仅供集群内部服务访问
  ports:
    - port: 80 # Service 暴露的端口
      targetPort: http-blog-api # 转发到 Deployment 容器的端口名
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: blog-api # 匹配上方的 Deployment 标签