# ‼ ️ 请注意：请将以下两个值替换为您在使用前在 GitLab 获得的真实用户名和令牌！
# 使用以下命令加入密钥：
#  1.Kubectl config use-context k3d-argocd
#  2.kubectl apply -f argocd-private-repo-secret.yaml
#  3.kubectl get secret inkspace-gitops-repo-pat -n argocd
apiVersion: v1
kind: Secret
metadata:
  name: inkspace-gitops-repo-pat
  namespace: argocd # 这里的命名空间必须与ArgoCD所在的命名空间一致
  labels:
    # ArgoCD 识别凭证的关键标签
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  # 1. 仓库 URL Argocd 使用该 URL 匹配密钥
  url: "http://gitlab.iceymoss.com/iceymoss/inkspace.git"

  # 2. 用户名：[请替换为你的真实GitLab用户名]
  username: "gitlab-ci"

  # 3. 令牌：[请用你的真实GitLab PAT字符串替换]
  password: ""

  # 4. repository type git
  type: "git"