apiVersion: v1
kind: Service
metadata:
  name: blog-api
  labels:
    app.kubernetes.io/name: blog-api
    project: inkspace
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-blog-api # 对应 Deployment 的端口名
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: blog-api