apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-web-ingress
spec:
  rules:
    - host: dev.web.test.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-web
                port:
                  number: 80